platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run build
  - npm run setup

deploy:
  release: v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: uF4xgF2iC1Sk+kVSBcijO6Fm0ML48yMBl/0WRBgn4Qg2BANbbak2Dr0HAHAB7KOa # your encrypted token from GitHub
  artifact: dist/installers/*.exe            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only