deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: uF4xgF2iC1Sk+kVSBcijO6Fm0ML48yMBl/0WRBgn4Qg2BANbbak2Dr0HAHAB7KOa # your encrypted token from GitHub
  artifact: dist/installers/*.exe            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only