platform:
  - x64

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

cache:
  - node_modules
  # - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version 
  - ps: Update-AppveyorBuild -Version "$env:package_version"
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run build
  - npm run setup

test: off

artifacts:
- path: dist/installers/*.exe
  name: myartifact

deploy:
  release: v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: uF4xgF2iC1Sk+kVSBcijO6Fm0ML48yMBl/0WRBgn4Qg2BANbbak2Dr0HAHAB7KOa # your encrypted token from GitHub
  artifacts: myartifact
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only